# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        pre-trained model: 1
        T5: 1
        mT5: 1
        NLP: 1
        BERT: 1
        language model: 1
        natural language processing: 1
        transfer learning: 1
        fine tuning: 1
        fine-tuning: 1
        pre-training: 1
        QA : 1
        summarization: 1
        question answering: 1
        calibration: 1

# 通知の閾値
score_threshold: 2
